spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testproject
    username: root
    password: hjz123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect